src/mysite/urls.py
from django.contrib             import admin
from django.urls                import path, re_path

from mysite.vistas              import vistas
from mysite.vistas.Super        import super
from mysite.vistas.Encargado    import encargado
from mysite.vistas.Business       import Business
from mysite.vistas.Bodeguero    import bodeguero

from django.conf                import settings
from django.conf.urls           import url
from django.conf.urls.static    import static
from django.contrib.auth.views  import login, logout

urlpatterns = [
    path('admin/',                              admin.site.urls),
    path('headers/',                            vistas.vista_actual_url),
    path('',                                    vistas.home),
    re_path(r'^Activate/([A-Z0-9]{15})/$',      vistas.Activate),
    re_path(r'^Login/$',                        login, name='login'),
    re_path(r'^Logout/$',                       logout, name='logout'),
    ##FUNCIONES DE SUPERUSUARIO
    re_path(r'^Usuarios/Crear/$',               super.requiere_staff(super.CrearUsuario)),
    re_path(r'^Usuarios/Ver/$',                 super.requiere_staff(super.VerUsuarios)),
    re_path(r'^Usuarios/Eliminar/(.+)/$',       super.requiere_staff(super.EliminarUsuario)),
    re_path(r'^Bodegas/Eliminar/(.+)/$',       super.requiere_staff(super.EliminarBodega)),
    re_path(r'^Bodegas/Crear/$',                super.requiere_staff(super.CrearBodega)),
    re_path(r'^Bodegas/Ver/$',                  super.requiere_staff(super.VerBodegas)),
    re_path(r'^Materiales/Cargar/$',            super.requiere_staff(super.CargarMateriales)),
    re_path(r'^Materiales/Ver/$',               super.requiere_staff(super.VerMateriales)),
    re_path(r'^Proveedores/Cargar/$',           super.requiere_staff(super.CargarProveedores)),
    re_path(r'^Proveedores/Ver/$',              super.requiere_staff(super.VerProveedores)),
    ##FUNCIONES DE Business DE NEGOCIOS
    re_path(r'^Obras/Ver/$',                    Business.requiere_Business(Business.VerObras)),
    re_path(r'^Obras/Crear/$',                  Business.requiere_Business(Business.CrearObra)),
    re_path(r'^Solicitudes/Crear/$',            Business.requiere_Business(Business.CrearSolicitud)),
    ##FUNCIONES DE BODEGUERO
    # re_path(r'^Solicitudes/Espera/$',         bodeguero.requiere_bodeguero(bodeguero.CrearObra)),
    # re_path(r'^Solicitudes/Listas/$',         bodeguero.requiere_bodeguero(bodeguero.CrearObra)),
    re_path(r'^Solicitudes/Buzon/$',     bodeguero.requiere_bodeguero(bodeguero.VerBuzon)),
    url(r'^Solicitudes/Detalle/(.*?)/$', bodeguero.requiere_bodeguero(bodeguero.VerDetalle), name='detallesSolicitud'),
    url(r'^Item/Stock/(.*?)/$',          bodeguero.requiere_bodeguero(bodeguero.ItemStock), name='revisarStock'),
    url(r'^Item/Reservar/(.*?)/(.*?)/$', bodeguero.requiere_bodeguero(bodeguero.ItemReservar), name='reservarItem'),
    url(r'^Item/Liberar/(.*?)/(.*?)/$',  bodeguero.requiere_bodeguero(bodeguero.ItemLiberar), name='liberarItem'),
    url(r'^Item/Solicitar/(.*?)/$',      bodeguero.requiere_bodeguero(bodeguero.ItemSolicitar), name='solicitarCompra'),
        url(r'^Item/Despachar/(.*?)/$',  bodeguero.requiere_bodeguero(bodeguero.ItemDespachar), name='despachar'),
    ##FUNCIONES DE ENCARGADO DE COMPRA
    re_path(r'^Encargos/Buzon/$',          encargado.requiere_encargado(encargado.VerBuzon), name='ComprasBuzon'),
    url(r'^Item/Cotizar/SendMail/(.*?)/$', encargado.requiere_encargado(encargado.Mail), name='CotizarSendMail'),
    url(r'^Item/Cotizar/(.*?)/$',          encargado.requiere_encargado(encargado.ItemCotizar), name='cotizarItem'),
    ##FUNCIONES DEL PROVEEDOR
    re_path(r'^Cotizar/Compra/([A-Z0-9]{15})/$',      encargado.RespuestaProveedor),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







"""
*****************************************************************************
mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

src/mysite/vistas/forms.py
from django import forms
from users.models import *
from django.contrib.auth.models import User

class FormCrearUsuario(forms.Form):
    first_name      = forms.CharField(required=True)
    last_name       = forms.CharField(required=True)
    email           = forms.CharField(required=True)
    tipo            = forms.CharField(max_length=10,widget=forms.Select(choices=ProfileType))
    telefono        = forms.CharField(required=True)

class FormCrearBodega(forms.Form):
    nombre          = forms.CharField(required=True)
    ubicacion       = forms.CharField(required=True)


class FormCrearObra(forms.Form):
    nombre              = forms.CharField(required=True)
    nombre_responsable  = forms.CharField(required=True)
    ubicacion           = forms.CharField(required=True)
    email               = forms.CharField(required=True)


class FormCrearSolicitud(forms.Form):
    obra            = forms.ModelChoiceField(queryset=Obra.objects.all(),widget=forms.Select())
    bodeguero       = forms.ModelChoiceField(queryset=Profile.objects.filter(tipo='B'),widget=forms.Select())
    # categoria       = forms.ModelChoiceField(queryset=MaterialCategoria.objects.all(),widget=forms.Select())
    material        = forms.ModelChoiceField(queryset=MaterialAbstracto.objects.all(),widget=forms.Select())
    cantidad        = forms.IntegerField(required=True)
    unidad          = forms.CharField(max_length=10,widget=forms.Select(choices=UnitType))
    descripcion     = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'descripción'}))


class FormCargarMateriales(forms.Form):
    data            = forms.FileField(required = True)
    bodega          = forms.ModelChoiceField(queryset=Bodega.objects.all())

class FormCargarProveedores(forms.Form):
    data            = forms.FileField(required = True)



class FormularioPassword(forms.Form):
    password            = forms.CharField(required=False,  widget=forms.TextInput(attrs={'placeholder': 'password'}))
    confirmPassword     = forms.CharField(required=False,  widget=forms.TextInput(attrs={'placeholder': 'confirm password'}))

class FormularioCotizacion(forms.Form):
    precio =forms.CharField(required=True,  widget=forms.TextInput(attrs={'placeholder': 'ingrese su precio sin iva..'}))
    fecha =forms.CharField(required=False,  widget=forms.TextInput(attrs={'placeholder': 'indique la fecha aproximada de entrega..'}))
    comentarios=forms.CharField(required=False,  widget=forms.TextInput(attrs={'placeholder': 'ingrese comentarios..'})) 

src/mysite/templates/Super/Super/formCargarMateriales.html
<section id="section-form" class="grid">
  <div class="content-wrap">
    <div class="form">
      {% if form.errors %}
        <p style="color: yellow;">Error.</p>
      {% endif %}
      <form action="" method="post" accept-charset="utf-8" enctype='multipart/form-data'>{% csrf_token %}
        <p style="color: #2ECC40;">{{ form.data.errors.as_text }}</p>
        <label for="data"><b>data<b></label>
        </br>
        {{ form.data }}

        <p style="color: #2ECC40;">{{ form.bodega.errors.as_text }}</p>
        <label for="id_bodega"><b>bodega<b></label>
        </br>
        {{ form.bodega }}
        <br><br><br>
        <input type="submit" value="Cargar materiales" />
        <input type="hidden" name="next" value="/" />

      </form>
    </div>
  </div>
</section>

src/mysite/templates/Super/Super/formCargarProveedores.html
<section id="section-form" class="grid">
  <div class="content-wrap">
    <div class="form">
      {% if form.errors %}
        <p style="color: yellow;">Error.</p>
      {% endif %}
      <form action="" method="post" accept-charset="utf-8" enctype='multipart/form-data'>{% csrf_token %}
        <p style="color: #2ECC40;">{{ form.data.errors.as_text }}</p>
        <label for="data"><b>data<b></label>
        </br>
        {{ form.data }}

        <br><br><br>
        <input type="submit" value="Cargar Proveedores" />
        <input type="hidden" name="next" value="/" />

      </form>
    </div>
  </div>
</section>

src/mysite/templates/Super/Super/formCrearBodega.html
<section id="section-form" class="grid">
    <div class="form">

      {% if form.errors %}
        <p style="color: yellow;">Error.</p>
      {% endif %}
      <form action="" method="post" accept-charset="utf-8">{% csrf_token %}

        <p style="color: #2ECC40;">{{ form.nombre.errors.as_text }}</p>
        <label for="id_nombre"><b>nombre<b></label>
        </br>
        <input type="text" name="nombre" value="" id="nombre">
        </br></br>

        <p style="color: #2ECC40;">{{ form.ubicacion.errors.as_text }}</p>
        <label for="id_ubicacion"><b>ubicacion<b></label>
        </br>
        <input type="text" name="ubicacion" value="" id="ubicacion">
        </br>

        <input type="submit" value="Crear Bodega" />
        <input type="hidden" name="next" value="/" />
        </br>
        </br>
      </form>
    </div>
  </div>
</section>

src/mysite/templates/Super/Super/formCrearUsuario.html
<section id="section-form" class="grid">
  <div class="content-wrap">
    <div class="form">

      {% if form.errors %}
        <p style="color: yellow;">Error.</p>
      {% endif %}
      <form action="" method="post" accept-charset="utf-8">{% csrf_token %}


        <p style="color: #2ECC40;">{{ form.first_name.errors.as_text }}</p>
        <label for="id_first_name"><b>first_name:<b></label>
        </br>
        <input type="text" name="first_name" value="" id="first_name">
        </br>

        <p style="color: #2ECC40;">{{ form.last_name.errors.as_text }}</p>
        <label for="id_last_name"><b>last_name<b></label>
        </br>
        <input type="text" name="last_name" value="" id="last_name">
        </br>

        <p style="color: #2ECC40;">{{ form.email.errors.as_text }}</p>
        <label for="id_email"><b>email<b></label>
        </br>
        <input type="text" name="email" value="" id="email">
        </br>

        <p style="color: #2ECC40;">{{ form.telefono.errors.as_text }}</p>
        <label for="id_telefono"><b>telefono<b></label>
        </br>
        <input type="text" name="telefono" value="" id="telefono">
        </br>

        <p style="color: #2ECC40;">{{ form.tipo.errors.as_text }}</p>
        <label for="tipo"><b>tipo<b></label>
        </br>
        {{ form.tipo }}

        <br><br><br>
        <input type="submit" value="Crear Usuario" />
        <input type="hidden" name="next" value="/Solicitudes" />
        </br>
        </br>









      </form>
    </div>
  </div>
</section>

src/mysite/templates/Super/Super/formVerBodegas.html
<section id="section-users" class="grid">

  {% if bodegas %}
      <ul>
      {% for bodega in bodegas %}
        <div class="content-users">
          <p>{{bodega.nombre}}, {{bodega.ubicacion}}</p>

        </div>
      {% endfor %}
      {% else %}
        <p>no hay bodegas</p>
  {% endif %}
</section>

src/mysite/templates/Super/Super/formVerUsuarios.html
<section id="section-users" class="grid">

  {% if perfiles %}
      <ul>
      {% for perfil in perfiles %}
        <div class="content-users">
          <p>{{perfil.user.first_name}} {{perfil.user.last_name}}, {{perfil.user.email}}, {{perfil.telefono}}, {{perfil.tipo}}, {{perfil.activo}}</p>
          <a href="/Usuarios/Eliminar/{{perfil.user.username}}" class="btn">Eliminar</a>
        </div>
      {% endfor %}
      {% else %}
        <p>no hay usuarios</p>
  {% endif %}
</section>

src/mysite/templates/Super/Super/nav.html
<!-- NAV -->
<nav >
<ul>
  <li><a class="active" href="/">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#about">About</a></li>
  <li class="dropdown">
    <a href="" class="dropbtn">Usuarios</a>
    <div class="dropdown-content">
      <a href="/Usuarios/Crear">Crear Usuarios</a>
      <a href="/Usuarios/Ver">Ver Usuarios</a>
    </div>
  </li>
</ul>
</nav>
<!-- <nav>
  <ul>
          <li class="dropdown">
            <a href="" class="dropbtn">Usuarios</a>
            <div class="dropdown-content">
              <a href="/Usuarios/Crear">Crear Usuarios</a>
              <a href="/Usuarios/Ver">Ver Usuarios</a>
            </div>
          </li>
          <li class="dropdown">
            <a href="" class="dropbtn">Bodegas</a>
            <div class="dropdown-content">
              <a href="/Bodegas/Crear">Crear Bodega</a>
              <a href="/Bodegas/Ver">Ver Bodegas</a>
            </div>
          </li>
        </li>
        <li class="dropdown">
          <a href="" class="dropbtn">Materiales</a>
          <div class="dropdown-content">
            <a href="/Materiales/Cargar">Cargar Materiales</a>

          </div>
        </li>

        <li class="dropdown">
          <a href="" class="dropbtn">Proveedores</a>
          <div class="dropdown-content">
            <a href="/Proveedores/Cargar">Cargar Proveedores</a>
          </div>
        </li>
      <li class="right"><a href="/Logout">Logout</a></li>
  </ul>
</nav> -->